//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use super::sea_orm_active_enums::PaymentMethodType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub payment_method_id: i32,
    pub customer_id: i32,
    pub payment_type: PaymentMethodType,
    pub is_default: Option<bool>,
    pub bank_name: Option<String>,
    pub account_holder_name: Option<String>,
    pub card_number: Option<String>,
    pub card_expiration_date: Option<Date>,
    pub card_type: Option<String>,
    pub iban: Option<String>,
    pub upi_id: Option<String>,
    pub bank_account_number: Option<String>,
    pub ifsc_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "(Column::CustomerId, Column::CustomerId)",
        to = "(super::customers::Column::CustomerId, super::customers::Column::CustomerId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
