//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "payment_method_type"
)]
pub enum PaymentMethodType {
    #[sea_orm(string_value = "card")]
    Card,
    #[sea_orm(string_value = "iban")]
    Iban,
    #[sea_orm(string_value = "netbanking")]
    Netbanking,
    #[sea_orm(string_value = "upi")]
    Upi,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "customer")]
    Customer,
    #[sea_orm(string_value = "supplier")]
    Supplier,
}
